# LIB'S

In [11]:
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

# Base Plano de Saúde

In [3]:
base_plano_saude = pd.read_csv('plano_saude.csv')
base_plano_saude

idade  custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [4]:
X_plano_saude = base_plano_saude.iloc[:,0].values
X_plano_saude

In [5]:
Y_plano_saude =  base_plano_saude.iloc[:,1].values
Y_plano_saude

array([ 871, 1132, 1242, 1356, 1488, 1638, 2130, 2454, 3066, 4090])

In [6]:
# correlacao
np.corrcoef(X_plano_saude, Y_plano_saude)

array([[1.        , 0.93091958],
       [0.93091958, 1.        ]])

In [8]:
X_plano_saude.shape

(10,)

In [9]:
# transformando em uma matriz
X_plano_saude = X_plano_saude.reshape(-1, 1)
X_plano_saude.shape

(10, 1)

In [15]:
regressor_plano_saude = LinearRegression()
regressor_plano_saude.fit(X_plano_saude, Y_plano_saude)

LinearRegression()

In [16]:
#b0
regressor_plano_saude.intercept_

-558.9490909090912

In [18]:
#b1
regressor_plano_saude.coef_

array([61.86787879])

In [20]:
# fazendo previsoes
previsoes = regressor_plano_saude.predict(X_plano_saude)
previsoes

array([ 554.67272727,  864.01212121, 1173.35151515, 1482.69090909,
       1792.03030303, 2101.36969697, 2410.70909091, 2720.04848485,
       3029.38787879, 3338.72727273])

In [26]:
# 'voltando' para o formato de vetor
X_plano_saude = X_plano_saude.ravel()

In [28]:
ax = px.scatter(x = X_plano_saude, y = Y_plano_saude)
ax.add_scatter(x = X_plano_saude, y = previsoes, name = 'Regressão')
ax.show()

In [29]:
# fazendo a previsao manualmente
regressor_plano_saude.intercept_ + regressor_plano_saude.coef_ * 29

array([1235.21939394])

In [31]:
regressor_plano_saude.predict([[29]])

array([1235.21939394])

In [40]:
#score
regressor_plano_saude.score((X_plano_saude.reshape(-1, 1)), (Y_plano_saude.reshape(-1, 1)))

0.8666112727879174