In [2]:
import pandas as pd

In [3]:
base = pd.read_csv('risco_credito.csv')

In [4]:
## Dividir a base de dados entre variaveis previsores e de classe

## Slide: todas as linhas. Colunas 0 até 4
previsores = base.iloc[:,0:4].values

##Classe --- Somente a coluna 4
classe = base.iloc[:,4].values

In [5]:
## Importando para o Naive Bayes

from sklearn.naive_bayes import GaussianNB

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
previsores[:,0] = labelencoder.fit_transform(previsores[:,0])
previsores[:,3] = labelencoder.fit_transform(previsores[:,3])
previsores[:,2] = labelencoder.fit_transform(previsores[:,2])
previsores[:,1] = labelencoder.fit_transform(previsores[:,1])

In [7]:
classificador = GaussianNB()
classificador.fit(previsores, classe)

GaussianNB(priors=None, var_smoothing=1e-09)

In [10]:
previsores

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [17]:
## Historia boa, dívida alta, garantias nenhuma, renda > 35
resultado = classificador.predict([[0,0,1,2]])
resultado

array(['baixo'], dtype='<U8')

In [19]:
## historia ruim, divida alta, garantias adequada, renda < 15
resultado2 = classificador.predict([[3,0,0,0]])
resultado2

array(['moderado'], dtype='<U8')

In [20]:
print(classificador.classes_)

['alto' 'baixo' 'moderado']


In [21]:
print(classificador.class_count_)

[6. 5. 3.]


In [22]:
print(classificador.class_prior_)

[0.42857143 0.35714286 0.21428571]


# Base 2 = Credit Bayes

In [25]:
import pandas as pd
import numpy as np

base = pd.read_csv('credit_data.csv')
base.loc[base.age < 0, 'age'] = 40.92
               
previsores = base.iloc[:, 1:4].values
classe = base.iloc[:, 4].values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
imputer = imputer.fit(previsores[:, 1:4])
previsores[:, 1:4] = imputer.transform(previsores[:, 1:4])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25, random_state=0)

from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

In [35]:
from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()

classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

In [41]:
## Percentual de acerto, ou seja, a comparacao entre treinamento x teste

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
precisao

0.938

In [44]:
## Matriz de confusao
matrix = confusion_matrix(classe_teste, previsoes)
matrix2 = pd.DataFrame(matrix)
matrix2

## Interpretando a matriz:
## 428 casos são da classe 0 e o algoritmo classificou como classe 0
## 8 casos sao da classe 0 mas o algoritmo classificou como 1
## 23 casos sao da classe 1, mas o algoritmo classificou como 0
## 41 casos sao da classe 1 e o algoritmo classificou como 1

## Total de registros classificados corretamente: somar as interseccoes == 428 + 41

0   1
0  428   8
1   23  41

# BASE 3 - CENSUS

In [68]:
import pandas as pd
import numpy as np

base = pd.read_csv('census.csv')

## Criando variavel previsores

previsores = base.iloc[:, 0:14].values

## Criando variavel classe
classe = base.iloc[:, 14].values

from sklearn.preprocessing import LabelEncoder
labelencoder_previsores = LabelEncoder()
##labels = labelencoder_previsores.fit_transform(previsores[:,1])

previsores[:,1] = labelencoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
previsores[:,6] = labelencoder_previsores.fit_transform(previsores[:,6])
previsores[:,7] = labelencoder_previsores.fit_transform(previsores[:,7])
previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
previsores[:,13] = labelencoder_previsores.fit_transform(previsores[:,13])

                
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_previsores = LabelEncoder()

onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])],
                                   remainder='passthrough')
previsores = onehotencorder.fit_transform(previsores).toarray()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size = 0.15, random_state =0)

from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

In [69]:
precisao

0.4767656090071648

In [70]:
matriz2 = pd.DataFrame(matriz)
matriz2

0     1
0  1172  2521
1    35  1157

## Melhorando o código

In [80]:
import pandas as pd
import numpy as np

base = pd.read_csv('census.csv')

## Criando variavel previsores

previsores = base.iloc[:, 0:14].values

## Criando variavel classe
classe = base.iloc[:, 14].values

from sklearn.preprocessing import LabelEncoder
labelencoder_previsores = LabelEncoder()
##labels = labelencoder_previsores.fit_transform(previsores[:,1])

previsores[:,1] = labelencoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
previsores[:,6] = labelencoder_previsores.fit_transform(previsores[:,6])
previsores[:,7] = labelencoder_previsores.fit_transform(previsores[:,7])
previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
previsores[:,13] = labelencoder_previsores.fit_transform(previsores[:,13])

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size = 0.15, random_state =0)

from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)



In [81]:
precisao

0.8057318321392016

In [82]:
matriz

array([[3528,  165],
       [ 784,  408]])

## Melhorando o codigo II

In [83]:
import pandas as pd
import numpy as np

base = pd.read_csv('census.csv')

## Criando variavel previsores

previsores = base.iloc[:, 0:14].values

## Criando variavel classe
classe = base.iloc[:, 14].values

from sklearn.preprocessing import LabelEncoder
labelencoder_previsores = LabelEncoder()
##labels = labelencoder_previsores.fit_transform(previsores[:,1])

previsores[:,1] = labelencoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelencoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelencoder_previsores.fit_transform(previsores[:,5])
previsores[:,6] = labelencoder_previsores.fit_transform(previsores[:,6])
previsores[:,7] = labelencoder_previsores.fit_transform(previsores[:,7])
previsores[:,8] = labelencoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelencoder_previsores.fit_transform(previsores[:,9])
previsores[:,13] = labelencoder_previsores.fit_transform(previsores[:,13])

onehotencorder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])],
                                   remainder='passthrough')
previsores = onehotencorder.fit_transform(previsores).toarray()

from sklearn.model_selection import train_test_split

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size = 0.15, random_state =0)

from sklearn.naive_bayes import GaussianNB
classificador = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)

from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

In [84]:
precisao

0.7950870010235415

In [85]:
matriz

array([[3515,  178],
       [ 823,  369]])